# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/ui/FLM_helper.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FLM_helper(object):
    def setupUi(self, FLM_helper):
        FLM_helper.setObjectName("FLM_helper")
        FLM_helper.resize(625, 394)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(FLM_helper.sizePolicy().hasHeightForWidth())
        FLM_helper.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FLM_helper)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Layout_Total = QtWidgets.QVBoxLayout()
        self.Layout_Total.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Layout_Total.setSpacing(10)
        self.Layout_Total.setObjectName("Layout_Total")
        spacerItem = QtWidgets.QSpacerItem(40, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.Layout_Total.addItem(spacerItem)
        self.Layout_SliceSelector = QtWidgets.QHBoxLayout()
        self.Layout_SliceSelector.setObjectName("Layout_SliceSelector")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.Layout_SliceSelector.addItem(spacerItem1)
        self.Layout_SliceSlider = QtWidgets.QHBoxLayout()
        self.Layout_SliceSlider.setObjectName("Layout_SliceSlider")
        self.Label_SliceSelector = QtWidgets.QLabel(FLM_helper)
        self.Label_SliceSelector.setMinimumSize(QtCore.QSize(60, 0))
        self.Label_SliceSelector.setWordWrap(True)
        self.Label_SliceSelector.setObjectName("Label_SliceSelector")
        self.Layout_SliceSlider.addWidget(self.Label_SliceSelector)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_SliceSlider.addItem(spacerItem2)
        self.Slider_SliceSelector = QtWidgets.QSlider(FLM_helper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Slider_SliceSelector.sizePolicy().hasHeightForWidth())
        self.Slider_SliceSelector.setSizePolicy(sizePolicy)
        self.Slider_SliceSelector.setMaximum(5)
        self.Slider_SliceSelector.setPageStep(5)
        self.Slider_SliceSelector.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_SliceSelector.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_SliceSelector.setTickInterval(1)
        self.Slider_SliceSelector.setObjectName("Slider_SliceSelector")
        self.Layout_SliceSlider.addWidget(self.Slider_SliceSelector)
        self.Number_SliceSelector = QtWidgets.QLCDNumber(FLM_helper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Number_SliceSelector.sizePolicy().hasHeightForWidth())
        self.Number_SliceSelector.setSizePolicy(sizePolicy)
        self.Number_SliceSelector.setObjectName("Number_SliceSelector")
        self.Layout_SliceSlider.addWidget(self.Number_SliceSelector)
        self.Layout_SliceSelector.addLayout(self.Layout_SliceSlider)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.Layout_SliceSelector.addItem(spacerItem3)
        self.Layout_Total.addLayout(self.Layout_SliceSelector)
        self.FluoChannels = QtWidgets.QHBoxLayout()
        self.FluoChannels.setSpacing(8)
        self.FluoChannels.setObjectName("FluoChannels")
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.FluoChannels.addItem(spacerItem4)
        self.Label_FluoChannels = QtWidgets.QLabel(FLM_helper)
        self.Label_FluoChannels.setObjectName("Label_FluoChannels")
        self.FluoChannels.addWidget(self.Label_FluoChannels)
        self.CheckBox_FluoChannel1 = QtWidgets.QCheckBox(FLM_helper)
        self.CheckBox_FluoChannel1.setChecked(True)
        self.CheckBox_FluoChannel1.setTristate(False)
        self.CheckBox_FluoChannel1.setObjectName("CheckBox_FluoChannel1")
        self.FluoChannels.addWidget(self.CheckBox_FluoChannel1)
        self.CheckBox_FluoChannel2 = QtWidgets.QCheckBox(FLM_helper)
        self.CheckBox_FluoChannel2.setChecked(True)
        self.CheckBox_FluoChannel2.setAutoExclusive(False)
        self.CheckBox_FluoChannel2.setTristate(False)
        self.CheckBox_FluoChannel2.setObjectName("CheckBox_FluoChannel2")
        self.FluoChannels.addWidget(self.CheckBox_FluoChannel2)
        self.CheckBox_FluoChannel3 = QtWidgets.QCheckBox(FLM_helper)
        self.CheckBox_FluoChannel3.setChecked(True)
        self.CheckBox_FluoChannel3.setObjectName("CheckBox_FluoChannel3")
        self.FluoChannels.addWidget(self.CheckBox_FluoChannel3)
        self.CheckBox_FluoChannel4 = QtWidgets.QCheckBox(FLM_helper)
        self.CheckBox_FluoChannel4.setChecked(True)
        self.CheckBox_FluoChannel4.setObjectName("CheckBox_FluoChannel4")
        self.FluoChannels.addWidget(self.CheckBox_FluoChannel4)
        self.CheckBox_FluoChannel5 = QtWidgets.QCheckBox(FLM_helper)
        self.CheckBox_FluoChannel5.setChecked(True)
        self.CheckBox_FluoChannel5.setObjectName("CheckBox_FluoChannel5")
        self.FluoChannels.addWidget(self.CheckBox_FluoChannel5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.FluoChannels.addItem(spacerItem5)
        self.Layout_Total.addLayout(self.FluoChannels)
        spacerItem6 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.Layout_Total.addItem(spacerItem6)
        self.line = QtWidgets.QFrame(FLM_helper)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Layout_Total.addWidget(self.line)
        self.Layout_HistoSelector = QtWidgets.QHBoxLayout()
        self.Layout_HistoSelector.setObjectName("Layout_HistoSelector")
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.Layout_HistoSelector.addItem(spacerItem7)
        self.Label_HistoSelector = QtWidgets.QLabel(FLM_helper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_HistoSelector.sizePolicy().hasHeightForWidth())
        self.Label_HistoSelector.setSizePolicy(sizePolicy)
        self.Label_HistoSelector.setScaledContents(True)
        self.Label_HistoSelector.setWordWrap(True)
        self.Label_HistoSelector.setObjectName("Label_HistoSelector")
        self.Layout_HistoSelector.addWidget(self.Label_HistoSelector)
        self.Radio_HistoSelector1 = QtWidgets.QRadioButton(FLM_helper)
        self.Radio_HistoSelector1.setObjectName("Radio_HistoSelector1")
        self.Layout_HistoSelector.addWidget(self.Radio_HistoSelector1)
        self.Radio_HistoSelector2 = QtWidgets.QRadioButton(FLM_helper)
        self.Radio_HistoSelector2.setObjectName("Radio_HistoSelector2")
        self.Layout_HistoSelector.addWidget(self.Radio_HistoSelector2)
        self.Radio_HistoSelector3 = QtWidgets.QRadioButton(FLM_helper)
        self.Radio_HistoSelector3.setObjectName("Radio_HistoSelector3")
        self.Layout_HistoSelector.addWidget(self.Radio_HistoSelector3)
        self.Radio_HistoSelector4 = QtWidgets.QRadioButton(FLM_helper)
        self.Radio_HistoSelector4.setObjectName("Radio_HistoSelector4")
        self.Layout_HistoSelector.addWidget(self.Radio_HistoSelector4)
        self.Radio_HistoSelector5 = QtWidgets.QRadioButton(FLM_helper)
        self.Radio_HistoSelector5.setObjectName("Radio_HistoSelector5")
        self.Layout_HistoSelector.addWidget(self.Radio_HistoSelector5)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.Layout_HistoSelector.addItem(spacerItem8)
        self.Layout_Total.addLayout(self.Layout_HistoSelector)
        self.Layout_MIP = QtWidgets.QHBoxLayout()
        self.Layout_MIP.setObjectName("Layout_MIP")
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_MIP.addItem(spacerItem9)
        self.PushButton_MIP = QtWidgets.QPushButton(FLM_helper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButton_MIP.sizePolicy().hasHeightForWidth())
        self.PushButton_MIP.setSizePolicy(sizePolicy)
        self.PushButton_MIP.setMinimumSize(QtCore.QSize(180, 0))
        self.PushButton_MIP.setCheckable(True)
        self.PushButton_MIP.setChecked(True)
        self.PushButton_MIP.setObjectName("PushButton_MIP")
        self.Layout_MIP.addWidget(self.PushButton_MIP)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_MIP.addItem(spacerItem10)
        self.Layout_Total.addLayout(self.Layout_MIP)
        self.Layout_AutoBC = QtWidgets.QHBoxLayout()
        self.Layout_AutoBC.setObjectName("Layout_AutoBC")
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_AutoBC.addItem(spacerItem11)
        self.Button_AutoBC = QtWidgets.QPushButton(FLM_helper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_AutoBC.sizePolicy().hasHeightForWidth())
        self.Button_AutoBC.setSizePolicy(sizePolicy)
        self.Button_AutoBC.setMinimumSize(QtCore.QSize(180, 0))
        self.Button_AutoBC.setObjectName("Button_AutoBC")
        self.Layout_AutoBC.addWidget(self.Button_AutoBC)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_AutoBC.addItem(spacerItem12)
        self.Layout_Total.addLayout(self.Layout_AutoBC)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 1, 2, 1, 1)
        self.Label_Brightness = QtWidgets.QLabel(FLM_helper)
        self.Label_Brightness.setMinimumSize(QtCore.QSize(60, 0))
        self.Label_Brightness.setWordWrap(True)
        self.Label_Brightness.setObjectName("Label_Brightness")
        self.gridLayout_2.addWidget(self.Label_Brightness, 0, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem14, 1, 5, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem15, 0, 5, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem16, 2, 2, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem17, 0, 2, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem18, 2, 5, 1, 1)
        self.Label_Alpha = QtWidgets.QLabel(FLM_helper)
        self.Label_Alpha.setMinimumSize(QtCore.QSize(60, 0))
        self.Label_Alpha.setWordWrap(True)
        self.Label_Alpha.setObjectName("Label_Alpha")
        self.gridLayout_2.addWidget(self.Label_Alpha, 2, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem19, 2, 0, 1, 1)
        self.Label_Contrast = QtWidgets.QLabel(FLM_helper)
        self.Label_Contrast.setMinimumSize(QtCore.QSize(60, 0))
        self.Label_Contrast.setWordWrap(True)
        self.Label_Contrast.setObjectName("Label_Contrast")
        self.gridLayout_2.addWidget(self.Label_Contrast, 1, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem20, 0, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem21, 1, 0, 1, 1)
        self.Slider_Contrast = QtWidgets.QSlider(FLM_helper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Slider_Contrast.sizePolicy().hasHeightForWidth())
        self.Slider_Contrast.setSizePolicy(sizePolicy)
        self.Slider_Contrast.setMaximum(100)
        self.Slider_Contrast.setProperty("value", 50)
        self.Slider_Contrast.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Contrast.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_Contrast.setObjectName("Slider_Contrast")
        self.gridLayout_2.addWidget(self.Slider_Contrast, 1, 3, 1, 1)
        self.Slider_Brightness = QtWidgets.QSlider(FLM_helper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Slider_Brightness.sizePolicy().hasHeightForWidth())
        self.Slider_Brightness.setSizePolicy(sizePolicy)
        self.Slider_Brightness.setMaximum(100)
        self.Slider_Brightness.setProperty("value", 50)
        self.Slider_Brightness.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Brightness.setInvertedAppearance(False)
        self.Slider_Brightness.setInvertedControls(False)
        self.Slider_Brightness.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_Brightness.setObjectName("Slider_Brightness")
        self.gridLayout_2.addWidget(self.Slider_Brightness, 0, 3, 1, 1)
        self.Slider_Alpha = QtWidgets.QSlider(FLM_helper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Slider_Alpha.sizePolicy().hasHeightForWidth())
        self.Slider_Alpha.setSizePolicy(sizePolicy)
        self.Slider_Alpha.setProperty("value", 99)
        self.Slider_Alpha.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Alpha.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_Alpha.setObjectName("Slider_Alpha")
        self.gridLayout_2.addWidget(self.Slider_Alpha, 2, 3, 1, 1)
        self.SpinBox_Brightness = QtWidgets.QSpinBox(FLM_helper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_Brightness.sizePolicy().hasHeightForWidth())
        self.SpinBox_Brightness.setSizePolicy(sizePolicy)
        self.SpinBox_Brightness.setWrapping(False)
        self.SpinBox_Brightness.setMaximum(100)
        self.SpinBox_Brightness.setProperty("value", 50)
        self.SpinBox_Brightness.setObjectName("SpinBox_Brightness")
        self.gridLayout_2.addWidget(self.SpinBox_Brightness, 0, 4, 1, 1)
        self.SpinBox_Contrast = QtWidgets.QSpinBox(FLM_helper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_Contrast.sizePolicy().hasHeightForWidth())
        self.SpinBox_Contrast.setSizePolicy(sizePolicy)
        self.SpinBox_Contrast.setMaximum(100)
        self.SpinBox_Contrast.setProperty("value", 50)
        self.SpinBox_Contrast.setObjectName("SpinBox_Contrast")
        self.gridLayout_2.addWidget(self.SpinBox_Contrast, 1, 4, 1, 1)
        self.SpinBox_Alpha = QtWidgets.QSpinBox(FLM_helper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_Alpha.sizePolicy().hasHeightForWidth())
        self.SpinBox_Alpha.setSizePolicy(sizePolicy)
        self.SpinBox_Alpha.setObjectName("SpinBox_Alpha")
        self.gridLayout_2.addWidget(self.SpinBox_Alpha, 2, 4, 1, 1)
        self.Layout_Total.addLayout(self.gridLayout_2)
        self.Label_Histogram = QtWidgets.QLabel(FLM_helper)
        self.Label_Histogram.setObjectName("Label_Histogram")
        self.Layout_Total.addWidget(self.Label_Histogram)
        spacerItem22 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.Layout_Total.addItem(spacerItem22)
        self.Layout_Total.setStretch(0, 1)
        self.Layout_Total.setStretch(1, 1)
        self.Layout_Total.setStretch(2, 1)
        self.Layout_Total.setStretch(3, 1)
        self.Layout_Total.setStretch(4, 1)
        self.Layout_Total.setStretch(5, 1)
        self.Layout_Total.setStretch(6, 1)
        self.Layout_Total.setStretch(7, 1)
        self.Layout_Total.setStretch(9, 1)
        self.Layout_Total.setStretch(10, 1)
        self.horizontalLayout.addLayout(self.Layout_Total)

        self.retranslateUi(FLM_helper)
        self.Slider_SliceSelector.valueChanged['int'].connect(self.Number_SliceSelector.display)
        self.Slider_Brightness.valueChanged['int'].connect(self.SpinBox_Brightness.setValue)
        self.SpinBox_Brightness.valueChanged['int'].connect(self.Slider_Brightness.setValue)
        self.Slider_Contrast.valueChanged['int'].connect(self.SpinBox_Contrast.setValue)
        self.SpinBox_Contrast.valueChanged['int'].connect(self.Slider_Contrast.setValue)
        self.SpinBox_Alpha.valueChanged['int'].connect(self.Slider_Alpha.setValue)
        self.Slider_Alpha.valueChanged['int'].connect(self.SpinBox_Alpha.setValue)
        QtCore.QMetaObject.connectSlotsByName(FLM_helper)

    def retranslateUi(self, FLM_helper):
        _translate = QtCore.QCoreApplication.translate
        FLM_helper.setWindowTitle(_translate("FLM_helper", "Image Properties"))
        self.Label_SliceSelector.setText(_translate("FLM_helper", "Stack Slice"))
        self.Label_FluoChannels.setText(_translate("FLM_helper", "Enabled Channels:"))
        self.CheckBox_FluoChannel1.setText(_translate("FLM_helper", "Channel 1"))
        self.CheckBox_FluoChannel2.setText(_translate("FLM_helper", "Channel 2"))
        self.CheckBox_FluoChannel3.setText(_translate("FLM_helper", "Channel 3"))
        self.CheckBox_FluoChannel4.setText(_translate("FLM_helper", "Channel 4"))
        self.CheckBox_FluoChannel5.setText(_translate("FLM_helper", "Channel 5"))
        self.Label_HistoSelector.setText(_translate("FLM_helper", "Histogram for:"))
        self.Radio_HistoSelector1.setText(_translate("FLM_helper", "Channel 1"))
        self.Radio_HistoSelector2.setText(_translate("FLM_helper", "Channel 2"))
        self.Radio_HistoSelector3.setText(_translate("FLM_helper", "Channel 3"))
        self.Radio_HistoSelector4.setText(_translate("FLM_helper", "Channel 4"))
        self.Radio_HistoSelector5.setText(_translate("FLM_helper", "Channel 5"))
        self.PushButton_MIP.setText(_translate("FLM_helper", "Maximum Intensity Projection"))
        self.Button_AutoBC.setText(_translate("FLM_helper", "Automatic Brightness/Contrast"))
        self.Label_Brightness.setText(_translate("FLM_helper", "Brightness"))
        self.Label_Alpha.setText(_translate("FLM_helper", "Alpha"))
        self.Label_Contrast.setText(_translate("FLM_helper", "Contrast"))
        self.Label_Histogram.setText(_translate("FLM_helper", "Here will be a histogram"))

